### ISSUE TITLE
No ChatGPT?

### ISSUE THREAD

**Issue by GCTales** [LJ3D/razor-arm#8]
void wiggle(arduinoSerial& Serial){
    std::vector<std::vector<double>> positions = {
        {100, 90, 150, 120, 90, 0},
        {100, 0, 60, 30, 0, 90},
        {100, 90, 150, 120, 90, 0},
        {100, 0, 60, 30, 0, 90},
        {100, 80, 140, 110, 80, 10},
        {100, 20, 40, 70, 10, 100},
        {100, 70, 130, 100, 70, 20},
        {100, 10, 30, 60, 0, 80},
        {100, 60, 120, 90, 60, 30},
        {100, 0, 20, 50, 350, 70},
        {100, 50, 110, 80, 50, 40},
        {100, 350, 10, 40, 340, 60}
        {157.5, 157.5, 187.5, 57.5, 157.5, 90}
    };
    for(auto p : positions){
        setJointPositions(Serial, p);
        std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    }
}

**Comment by lucianjames** [comment]
skill issue
